//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDdoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_ID { get; set; }
        public string Time { get; set; }
        public Nullable<int> ID { get; set; }
        public string Patient_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Date { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
