//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDdoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int hospital_ID { get; set; }
        public string hospital_Name { get; set; }
        public string location { get; set; }
    }
}
