//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDdoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Medicine_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Medicine_Name { get; set; }
        public Nullable<int> Medicine_Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Description { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
