//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDdoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int Sample_ID { get; set; }
        public string Sample_Name { get; set; }
        public Nullable<int> Sample_Charge { get; set; }
        public string Sample_Description { get; set; }
    }
}
